### PR TITLE
Fixed small issue with ordering of statements in `extract_text`

### PR DESCRIPTION
**Pull request by alexreg**
`chars = to_list(chars)` and `len(chars)` need to be swapped to avoid error sometimes.

Fixes issue #386.

### CODE REVIEW

**Review by samkit-jain — CHANGES_REQUESTED** [review]
Appreciate you opening a PR @alexreg Request you to add a test case that passes on this commit and fails otherwise.

**Comment by alexreg** [comment]
@samkit-jain Sure, will do. How do I run tests though? Ideally, this should be documented in the README.

**Comment by jsvine** [comment]
Thanks, @alexreg and @samkit-jain. I really appreciate the test addition — generally ... but also specifically in this case, because it clarifies what's going on here: The previous code didn't work when the `chars` argument is a generator. It might be a fairly edge-case situation, but since the fix is very straightforward and doesn't affect performance, I'll merge it.

**Comment by jsvine** [comment]
And, yes, @alexreg — it's definitely worth us adding PR guidelines (including re. tests). Will open an issue on that and self-assign.

**Comment by alexreg** [comment]
@jsvine That was my thought too, basically. Thanks for merging.

**Pull request merged**
