### PR TITLE
fix duplicates in extract_text/extract_words/extract_tables

### PR DESCRIPTION
**Pull request by xv44586**
https://github.com/jsvine/pdfplumber/issues/71

### CODE REVIEW

**Review by samkit-jain — COMMENTED** [review]
Thanks for the PR @xv44586 Could you also please add a test case for the same?

**Comment by xv44586** [comment]
> Thanks for the PR @xv44586 Could you also please add a test case for the same?

done! please check this out

**Comment by jsvine** [comment]
Thank you, I will review this.

**Comment by jsvine** [comment]
Many thanks for providing this inspiration and the test, @xv44586! I think that this proposed solution is slightly more complex than it needs to be; rather than adding a parameter to every relevant method, we can just provide a `utils` and `Page` method that allows users to deduplicate chars beforehand. In https://github.com/jsvine/pdfplumber/commit/04fd56ac405fd753e7f9c826ce103459013f2e71 I have added this logic (available in `develop` and in the next release), using your very helpful test and have credited you in the README. Thanks again 👍

**Pull request closed without merging**
