### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jakobdo**
keep_blank_chars no longer supported as table_setting

### CODE REVIEW

**Comment by jsvine** [comment]
Hi @jakobdo, and thanks for your interest in improving `pdfplumber`'s documentation. I'm a bit confused by this particular PR, however. The changes suggested here are for the *general text extraction* portion of the documentation, not the table-extraction section. Could you provide more details about the intent of this PR?

**Comment by jsvine** [comment]
Just checking back on this, @jakobdo. Thanks!

**Comment by Pk13055** [comment]
Please confirm if this setting has been deprecated, and update the `README` if so.

```sh
  File "<***>/lib/python3.11/site-packages/pdfplumber/page.py", line 413, in extract_tables
    tset = TableSettings.resolve(table_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<***>/lib/python3.11/site-packages/pdfplumber/table.py", line 551, in resolve
    return cls(**core_settings)
           ^^^^^^^^^^^^^^^^^^^^
TypeError: TableSettings.__init__() got an unexpected keyword argument 'keep_blank_chars'
```

**Comment by jsvine** [comment]
@Pk13055 Ah, I see what you mean. Thank you, good catch. When using table extraction, it should be `text_keep_blank_chars`. Documentation now updated: 401b82c. Closing for now, but let me know if something about this is still unclear.

**Pull request closed without merging**
